### ISSUE TITLE
Some plural-only Czech words are missing

### ISSUE THREAD

**Issue by Vuizur** [xxyzz/Proficiency#21]
Some plural-only Czech words such as plavky, kalhoty, záda seem to be fine in the Kaikki data and show up on kaikki.org, but for some reason don't appear in the WordDumb sqlite database. I am not sure what might be the reason.

(Thanks again for making Czech possible! It works really well.)

**Comment by xxyzz** [comment]
https://github.com/xxyzz/Proficiency/releases/tag/v0.5.17 contains these words, you'll need to install the latest test plugin and click the "restore defaults" button in the customize lemmas window to download the new lemmas db file.

**Comment by Vuizur** [comment]
Awesome, it works now 👍👍👍 Thanks a lot!
